### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by guoguangfeng** [jinevening/IONN-client#1]
I try to install IONN client in Nvidia Jenson Nano under CPU-only mode. run make all -j4,But it dont't compile.
My hardware and software :
     hardware: Nvidia Jenson Nano (set CPU_ONLY := 1 in ) /Memory 4GB/CPU: ARMv8 rev1(v8l)*4
     software :
            ubuntu 18.04 LTS 64-bit
            cmake version 3.10.2 
            g++ (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0

The error tips is below:

CXX tools/upgrade_net_proto_binary.cpp
tools/caffe.cpp: In function ‘int train()’:
tools/caffe.cpp:243:3: error: reference to ‘shared_ptr’ is ambiguous
   shared_ptr<caffe::Solver<float> >
   ^~~~~~~~~~
In file included from /usr/include/boost/throw_exception.hpp:42:0,
                 from /usr/include/boost/function/detail/prologue.hpp:15,
                 from /usr/include/boost/function.hpp:24,
                 from /usr/include/boost/algorithm/string/detail/find_iterator.hpp:18,
                 from /usr/include/boost/algorithm/string/find_iterator.hpp:24,
                 from /usr/include/boost/algorithm/string/iter_find.hpp:27,
                 from /usr/include/boost/algorithm/string/split.hpp:16,
                 from /usr/include/boost/algorithm/string.hpp:23,
                 from tools/caffe.cpp:14:
/usr/include/boost/exception/exception.hpp:19:44: note: candidates are: template<class T> class boost::shared_ptr
 namespace boost { template <class T> class shared_ptr; };
                                            ^~~~~~~~~~
In file included from /usr/include/c++/7/bits/shared_ptr.h:52:0,
                 from /usr/include/c++/7/memory:81,
                 from /usr/include/boost/function/function_base.hpp:16,
                 from /usr/include/boost/function/detail/prologue.hpp:17,
                 from /usr/include/boost/function.hpp:24,
                 from /usr/include/boost/algorithm/string/detail/find_iterator.hpp:18,
                 from /usr/include/boost/algorithm/string/find_iterator.hpp:24,
                 from /usr/include/boost/algorithm/string/iter_find.hpp:27,
                 from /usr/include/boost/algorithm/string/split.hpp:16,
                 from /usr/include/boost/algorithm/string.hpp:23,
                 from tools/caffe.cpp:14:
/usr/include/c++/7/bits/shared_ptr_base.h:347:11: note:                 template<class _Tp> class std::shared_ptr
     class shared_ptr;
           ^~~~~~~~~~
tools/caffe.cpp:243:35: error: expected primary-expression before ‘>’ token
   shared_ptr<caffe::Solver<float> >
                                   ^
tools/caffe.cpp:244:7: error: ‘solver’ was not declared in this scope
       solver(caffe::SolverRegistry<float>::CreateSolver(solver_param));
       ^~~~~~
tools/caffe.cpp:244:7: note: suggested alternative: ‘socket’
       solver(caffe::SolverRegistry<float>::CreateSolver(solver_param));
       ^~~~~~
       socket
tools/caffe.cpp: In function ‘int time()’:
tools/caffe.cpp:376:42: error: template argument 1 is invalid
   const vector<shared_ptr<Layer<float> > >& layers = caffe_net.layers();
                                          ^
tools/caffe.cpp:376:42: error: template argument 2 is invalid
tools/caffe.cpp:376:70: error: invalid initialization of reference of type ‘const int&’ from expression of type ‘const std::vector<boost::shared_ptr<caffe::Layer<float> >, std::allocator<boost::shared_ptr<caffe::Layer<float> > > >’
   const vector<shared_ptr<Layer<float> > >& layers = caffe_net.layers();
                                                      ~~~~~~~~~~~~~~~~^~
tools/caffe.cpp:388:53: error: request for member ‘size’ in ‘layers’, which is of non-class type ‘const int’
   std::vector<double> forward_time_per_layer(layers.size(), 0.0);
                                                     ^~~~
tools/caffe.cpp:389:54: error: request for member ‘size’ in ‘layers’, which is of non-class type ‘const int’
   std::vector<double> backward_time_per_layer(layers.size(), 0.0);
                                                      ^~~~
tools/caffe.cpp:396:32: error: request for member ‘size’ in ‘layers’, which is of non-class type ‘const int’
     for (int i = 0; i < layers.size(); ++i) {
                                ^~~~
tools/caffe.cpp:398:15: error: invalid types ‘const int[int]’ for array subscript
       layers[i]->Forward(bottom_vecs[i], top_vecs[i]);
               ^
tools/caffe.cpp:403:25: error: request for member ‘size’ in ‘layers’, which is of non-class type ‘const int’
     for (int i = layers.size() - 1; i >= 0; --i) {
                         ^~~~
tools/caffe.cpp:405:15: error: invalid types ‘const int[int]’ for array subscript
       layers[i]->Backward(top_vecs[i], bottom_need_backward[i],
               ^
tools/caffe.cpp:418:30: error: request for member ‘size’ in ‘layers’, which is of non-class type ‘const int’
   for (int i = 0; i < layers.size(); ++i) {
                              ^~~~
tools/caffe.cpp:419:46: error: invalid types ‘const int[int]’ for array subscript
     const caffe::string& layername = layers[i]->layer_param().name();
                                              ^
tools/caffe.cpp: In function ‘caffe::SolverAction::Enum GetRequestedAction(const string&)’:
tools/caffe.cpp:177:1: warning: control reaches end of non-void function [-Wreturn-type]
 }

**Comment by jinevening** [comment]
It seems that the compiler cannot find the definition of "shared_ptr".

Please add "boost::" to all places where "shared_ptr" is used.

**Comment by guoguangfeng** [comment]
> It seems that the compiler cannot find the definition of "shared_ptr".
> 
> Please add "boost::" to all places where "shared_ptr" is used.

I modify the code according to this method, and successfully  install the IONN client on the Jenson Nano with CPU-only model. Thank you!
