### ISSUE TITLE
How to measure the server-side loading time?

### ISSUE THREAD

**Issue by guoguangfeng** [jinevening/IONN-client#2]
Hi, I have a question about server-side loading time(as below the variable loading_time_s). I read your code about [IONN-client/src/caffe/execution_graph.cpp] (as below Line 170-181). How to measure the server-side loading time? This is a base of building the linear regression. Thank you.

void ExecutionGraph::setUpExecutionGraphLayers() {
......
    // update loading time
Line 170:    if (strcmp(layers[i]->type(), "Convolution") == 0) {
      float filters = static_cast<float>(layers[i]->layer_param().convolution_param().num_output());
      current_layer->loading_time_s += 3.0e-3 * filters + 0.7;
    }
    else if (strcmp(layers[i]->type(), "InnerProduct") == 0) {
      float neurons = static_cast<float>(layers[i]->layer_param().inner_product_param().num_output());
      current_layer->loading_time_s += 3.0e-7 * (neurons * static_cast<float>(input_f_size)) + 1.3;
    }
    else {
      // very small loading time for other types of layers
 Line 181:        current_layer->loading_time_s += 0.00005;
...
}

**Comment by jinevening** [comment]
You do not have to consider server-side loading time when doing linear regression.

We made loading_time_s for future research, but it is currently not used. (the value of loading_time_s is initialized as 0 and does not change)
