### ISSUE TITLE
Question about Execute Crash

### ISSUE THREAD

**Issue by guoguangfeng** [jinevening/IONN-client#3]
Dear Sir,
      I modify IONN-client/partitioning/classification.cpp, below as:
      Line 671:   const bool original_algorithm = false;
      and Run classification.bin.
   The console  information is below. How to debug this error? Do you give a suggent about  the C++ IDE. Thanks you!
ggf@ggf-desktop:~/ElasticDNN1/IONN-client$ ./build/examples/partitioning2/classification.bin \
>   models/bvlc_alexnet/deploy.prototxt \
>   models/bvlc_alexnet/bvlc_alexnet.caffemodel  \
>   data/ilsvrc12/imagenet_mean.binaryproto  \
>   data/ilsvrc12/synset_words.txt  \
>   models/bvlc_alexnet/client_model1.txt  \
>   models/bvlc_alexnet/server_prediction_model1.txt  \
>   40  \
>   cat.jpg  \
>   0  \
>   incremental  \
>   time  \
>   use_file \
>   192.168.1.90
execute start:2020-01-10 21:31:24
Dominators of output layer: 1 3 4 5 7 8 9 11 13 15 16 19 22
# of Dominators: 13
There are 13 layers
name : conv1 input_feature: 618348 output_feature: 1161600 model_size: 139776 exec_time_c: 95.9674 exec_time_s: 11.6099 loading_time_s: 0.988
name : norm1 input_feature: 1161600 output_feature: 1161600 model_size: 0 exec_time_c: 39.5537 exec_time_s: 4.59046 loading_time_s: 0.0001
name : pool1 input_feature: 1161600 output_feature: 279936 model_size: 0 exec_time_c: 17.8863 exec_time_s: 1.08056 loading_time_s: 5e-05
name : conv2 input_feature: 279936 output_feature: 746496 model_size: 1229824 exec_time_c: 205.727 exec_time_s: 21.8116 loading_time_s: 1.468
name : norm2 input_feature: 746496 output_feature: 746496 model_size: 0 exec_time_c: 29.1358 exec_time_s: 3.01084 loading_time_s: 0.0001
name : pool2 input_feature: 746496 output_feature: 173056 model_size: 0 exec_time_c: 12.2637 exec_time_s: 0.72734 loading_time_s: 5e-05
name : conv3 input_feature: 173056 output_feature: 259584 model_size: 3540480 exec_time_c: 113.685 exec_time_s: 17.4095 loading_time_s: 1.852
name : conv4 input_feature: 259584 output_feature: 259584 model_size: 2655744 exec_time_c: 96.897 exec_time_s: 13.2976 loading_time_s: 1.85205
name : conv5 input_feature: 259584 output_feature: 173056 model_size: 1770496 exec_time_c: 74.2967 exec_time_s: 9.29986 loading_time_s: 1.46805
name : pool5 input_feature: 173056 output_feature: 36864 model_size: 0 exec_time_c: 5.74844 exec_time_s: 0.23 loading_time_s: 0.0001
name : fc6 input_feature: 36864 output_feature: 16384 model_size: 151011328 exec_time_c: 342.224 exec_time_s: 53.7221 loading_time_s: 46.5985
name : fc7 input_feature: 16384 output_feature: 16384 model_size: 67125248 exec_time_c: 143.545 exec_time_s: 24.3946 loading_time_s: 21.4328
name : fc8 input_feature: 16384 output_feature: 4000 model_size: 16388000 exec_time_c: 34.9957 exec_time_s: 6.02248 loading_time_s: 6.2153
(0, 1, 0)
(1, 2, 117.941)
(2, 3, 39.2581)
(3, 4, 221.558)
(1, 4, 95.9674)
(4, 5, 221.558)
(5, 6, 4.59056)
(6, 7, 221.558)
(4, 7, 39.5537)
(3, 5, 0)
(7, 8, 221.558)
(8, 9, 1.08061)
(9, 10, 53.3936)
(7, 10, 17.8863)
(6, 8, 0)
(10, 11, 53.3936)
(11, 12, 257.85)
(12, 13, 142.383)
(10, 13, 205.727)
(9, 11, 0)
(13, 14, 142.383)
(14, 15, 3.01094)
(15, 16, 142.383)
(13, 16, 29.1358)
(12, 14, 0)
(16, 17, 142.383)
(17, 18, 0.72739)
(18, 19, 33.0078)
(16, 19, 12.2637)
(15, 17, 0)
(19, 20, 33.0078)
(20, 21, 694.554)
(21, 22, 49.5117)
(19, 22, 113.685)
(18, 20, 0)
(22, 23, 49.5117)
(23, 24, 521.693)
(24, 25, 49.5117)
(22, 25, 96.897)
(21, 23, 0)
(25, 26, 49.5117)
(26, 27, 348.463)
(27, 28, 33.0078)
(25, 28, 74.2967)
(24, 26, 0)
(28, 29, 33.0078)
(29, 30, 0.2301)
(30, 31, 7.03125)
(28, 31, 5.74844)
(27, 29, 0)
(31, 32, 7.03125)
(32, 33, 28903.4)
(33, 34, 3.125)
(31, 34, 342.224)
(30, 32, 0)
(34, 35, 3.125)
(35, 36, 12849)
(36, 37, 3.125)
(34, 37, 143.545)
(33, 35, 0)
(37, 38, 3.125)
(38, 39, 3138)
(39, 40, 0.762939)
(37, 40, 34.9957)
(36, 38, 0)
1,Partitioning previous time taken: 0.000860093 s
Partitioning plans old
0. (1, 22) 
->12
expected speed local: 1211.93
expected speed after 3 5: 1076.99
expected speed after 0 2: 1005.43
expected speed after 6 6: 926.34
expected speed after 7 7: 843.249
expected speed after 8 9: 730.593
expected speed after 10 10: 467.034
expected speed after 11 11: 360.708
expected speed after 12 12: 332.504
Partitioning new time taken: 0.00159996 s
Partitioning plans
0. (5, 8) 
->1. (1, 8) 
->2. (1, 9) 
->3. (1, 11) 
->4. (1, 15) 
->5. (1, 16) 
->6. (1, 19) 
->7. (1, 22) 
->---------- Prediction for cat.jpg ----------
forward thread woken
[[[Offloading 0]]]
upload woken
plan aim:5 8
SingleIteration0: 5 8 -1 -1
complete chunk: 5 8, prototxt: 1 8
Original bottom name: pool1
Original bottom name: pool1
Serializing 4 layers
bottom_vecs_[offloading_point][0].size() 1plan aim:1 8
SingleIteration0: 1 4 -1 -1
complete chunk: 1 8, prototxt: 1 8
Original bottom name: data
Original bottom name: data
Serializing 4 layers
plan aim:1 9
SingleIteration0: -1 -1 9 9
complete chunk: 1 9, prototxt: 1 9
Original bottom name: data
Serializing 1 layers
Received 0 bytes
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >'
  what():  write: Connection reset by peer
Aborted (core dumped)

**Comment by danielshin32** [comment]
The current implementation have problems when the next partition does not operate directly on the output of the previous partition.
That is, a plan of (1, 2) -> (1, 3) works fine but (2, 3) -> (1, 3) or (1, 2) -> (1->2), (5->6) does not.
We currently do not know the exact reasoning for this.
