### ISSUE TITLE
Hi, how do you get prediction_model.txt and server_prediction_model.txt?

### ISSUE THREAD

**Issue by Calomey** [jinevening/IONN-client#4]
Hi, how do you get prediction_model.txt and server_prediction_model.txt?

**Comment by jinevening** [comment]
It was profiled offline using `caffe time` interface.

PTAL https://caffe.berkeleyvision.org/tutorial/interfaces.html

**Comment by Calomey** [comment]
> It was profiled offline using `caffe time` interface.
> 
> PTAL https://caffe.berkeleyvision.org/tutorial/interfaces.html

thanks
